// Code generated by protoc-gen-go.
// source: file_guide.proto
// DO NOT EDIT!

/*
Package fileguide is a generated protocol buffer package.

It is generated from these files:
	file_guide.proto

It has these top-level messages:
	InitConnectionData
	FileChunk
	Filename
	FileSummary
*/
package fileguide

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InitConnectionData struct {
	NBPort int64   `protobuf:"varint,1,opt,name=NBPort,json=nBPort" json:"NBPort,omitempty"`
	Ports  []int64 `protobuf:"varint,2,rep,packed,name=Ports,json=ports" json:"Ports,omitempty"`
}

func (m *InitConnectionData) Reset()                    { *m = InitConnectionData{} }
func (m *InitConnectionData) String() string            { return proto.CompactTextString(m) }
func (*InitConnectionData) ProtoMessage()               {}
func (*InitConnectionData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InitConnectionData) GetNBPort() int64 {
	if m != nil {
		return m.NBPort
	}
	return 0
}

func (m *InitConnectionData) GetPorts() []int64 {
	if m != nil {
		return m.Ports
	}
	return nil
}

type FileChunk struct {
	Chunk      []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Filename   string `protobuf:"bytes,2,opt,name=filename" json:"filename,omitempty"`
	BlockID    int64  `protobuf:"varint,3,opt,name=blockID" json:"blockID,omitempty"`
	TotalBlock int64  `protobuf:"varint,4,opt,name=totalBlock" json:"totalBlock,omitempty"`
}

func (m *FileChunk) Reset()                    { *m = FileChunk{} }
func (m *FileChunk) String() string            { return proto.CompactTextString(m) }
func (*FileChunk) ProtoMessage()               {}
func (*FileChunk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FileChunk) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

func (m *FileChunk) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileChunk) GetBlockID() int64 {
	if m != nil {
		return m.BlockID
	}
	return 0
}

func (m *FileChunk) GetTotalBlock() int64 {
	if m != nil {
		return m.TotalBlock
	}
	return 0
}

type Filename struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Filename) Reset()                    { *m = Filename{} }
func (m *Filename) String() string            { return proto.CompactTextString(m) }
func (*Filename) ProtoMessage()               {}
func (*Filename) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Filename) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FileSummary struct {
	// The number of points received.
	ChunkCount int64 `protobuf:"varint,1,opt,name=chunk_count,json=chunkCount" json:"chunk_count,omitempty"`
	// The number of known features passed while traversing the route.
	ByteCount int64 `protobuf:"varint,2,opt,name=byte_count,json=byteCount" json:"byte_count,omitempty"`
	// The duration of the traversal in seconds.
	ElapsedTime int64  `protobuf:"varint,3,opt,name=elapsed_time,json=elapsedTime" json:"elapsed_time,omitempty"`
	BlockID     int64  `protobuf:"varint,4,opt,name=blockID" json:"blockID,omitempty"`
	TotalBlock  int64  `protobuf:"varint,5,opt,name=totalBlock" json:"totalBlock,omitempty"`
	Name        string `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
}

func (m *FileSummary) Reset()                    { *m = FileSummary{} }
func (m *FileSummary) String() string            { return proto.CompactTextString(m) }
func (*FileSummary) ProtoMessage()               {}
func (*FileSummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FileSummary) GetChunkCount() int64 {
	if m != nil {
		return m.ChunkCount
	}
	return 0
}

func (m *FileSummary) GetByteCount() int64 {
	if m != nil {
		return m.ByteCount
	}
	return 0
}

func (m *FileSummary) GetElapsedTime() int64 {
	if m != nil {
		return m.ElapsedTime
	}
	return 0
}

func (m *FileSummary) GetBlockID() int64 {
	if m != nil {
		return m.BlockID
	}
	return 0
}

func (m *FileSummary) GetTotalBlock() int64 {
	if m != nil {
		return m.TotalBlock
	}
	return 0
}

func (m *FileSummary) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*InitConnectionData)(nil), "fileguide.InitConnectionData")
	proto.RegisterType((*FileChunk)(nil), "fileguide.FileChunk")
	proto.RegisterType((*Filename)(nil), "fileguide.Filename")
	proto.RegisterType((*FileSummary)(nil), "fileguide.FileSummary")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FileGuide service

type FileGuideClient interface {
	SaveFile(ctx context.Context, opts ...grpc.CallOption) (FileGuide_SaveFileClient, error)
	GetFile(ctx context.Context, in *Filename, opts ...grpc.CallOption) (FileGuide_GetFileClient, error)
	InitConnection(ctx context.Context, in *InitConnectionData, opts ...grpc.CallOption) (*InitConnectionData, error)
}

type fileGuideClient struct {
	cc *grpc.ClientConn
}

func NewFileGuideClient(cc *grpc.ClientConn) FileGuideClient {
	return &fileGuideClient{cc}
}

func (c *fileGuideClient) SaveFile(ctx context.Context, opts ...grpc.CallOption) (FileGuide_SaveFileClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FileGuide_serviceDesc.Streams[0], c.cc, "/fileguide.FileGuide/SaveFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileGuideSaveFileClient{stream}
	return x, nil
}

type FileGuide_SaveFileClient interface {
	Send(*FileChunk) error
	CloseAndRecv() (*FileSummary, error)
	grpc.ClientStream
}

type fileGuideSaveFileClient struct {
	grpc.ClientStream
}

func (x *fileGuideSaveFileClient) Send(m *FileChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fileGuideSaveFileClient) CloseAndRecv() (*FileSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(FileSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileGuideClient) GetFile(ctx context.Context, in *Filename, opts ...grpc.CallOption) (FileGuide_GetFileClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FileGuide_serviceDesc.Streams[1], c.cc, "/fileguide.FileGuide/GetFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileGuideGetFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FileGuide_GetFileClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type fileGuideGetFileClient struct {
	grpc.ClientStream
}

func (x *fileGuideGetFileClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileGuideClient) InitConnection(ctx context.Context, in *InitConnectionData, opts ...grpc.CallOption) (*InitConnectionData, error) {
	out := new(InitConnectionData)
	err := grpc.Invoke(ctx, "/fileguide.FileGuide/InitConnection", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FileGuide service

type FileGuideServer interface {
	SaveFile(FileGuide_SaveFileServer) error
	GetFile(*Filename, FileGuide_GetFileServer) error
	InitConnection(context.Context, *InitConnectionData) (*InitConnectionData, error)
}

func RegisterFileGuideServer(s *grpc.Server, srv FileGuideServer) {
	s.RegisterService(&_FileGuide_serviceDesc, srv)
}

func _FileGuide_SaveFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileGuideServer).SaveFile(&fileGuideSaveFileServer{stream})
}

type FileGuide_SaveFileServer interface {
	SendAndClose(*FileSummary) error
	Recv() (*FileChunk, error)
	grpc.ServerStream
}

type fileGuideSaveFileServer struct {
	grpc.ServerStream
}

func (x *fileGuideSaveFileServer) SendAndClose(m *FileSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fileGuideSaveFileServer) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FileGuide_GetFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Filename)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileGuideServer).GetFile(m, &fileGuideGetFileServer{stream})
}

type FileGuide_GetFileServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type fileGuideGetFileServer struct {
	grpc.ServerStream
}

func (x *fileGuideGetFileServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _FileGuide_InitConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitConnectionData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileGuideServer).InitConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fileguide.FileGuide/InitConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileGuideServer).InitConnection(ctx, req.(*InitConnectionData))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileGuide_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fileguide.FileGuide",
	HandlerType: (*FileGuideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitConnection",
			Handler:    _FileGuide_InitConnection_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SaveFile",
			Handler:       _FileGuide_SaveFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetFile",
			Handler:       _FileGuide_GetFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "file_guide.proto",
}

func init() { proto.RegisterFile("file_guide.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x6e, 0xe2, 0x30,
	0x10, 0x86, 0x31, 0x81, 0x40, 0x06, 0xb4, 0x5a, 0xcd, 0x22, 0x14, 0x45, 0x82, 0x65, 0x7d, 0xca,
	0x09, 0xad, 0xda, 0x4b, 0x0f, 0x3d, 0x01, 0x02, 0x71, 0xa9, 0x50, 0xe8, 0x1d, 0x99, 0xe0, 0xb6,
	0x16, 0x89, 0x8d, 0xc0, 0x69, 0xc5, 0xcb, 0xf5, 0x2d, 0xfa, 0x3e, 0x95, 0x4d, 0x48, 0x81, 0x56,
	0x9c, 0xec, 0xff, 0x9b, 0xf1, 0x8c, 0x7f, 0x7b, 0xe0, 0xf7, 0x93, 0x48, 0xf8, 0xe2, 0x39, 0x13,
	0x2b, 0xde, 0xdf, 0x6c, 0x95, 0x56, 0xe8, 0x19, 0x62, 0x01, 0x1d, 0x00, 0x4e, 0xa5, 0xd0, 0x43,
	0x25, 0x25, 0x8f, 0xb5, 0x50, 0x72, 0xc4, 0x34, 0xc3, 0x36, 0xb8, 0x0f, 0x83, 0x99, 0xda, 0x6a,
	0x9f, 0xf4, 0x48, 0xe8, 0x44, 0xae, 0xb4, 0x0a, 0x5b, 0x50, 0x35, 0xeb, 0xce, 0x2f, 0xf7, 0x9c,
	0xd0, 0x89, 0xaa, 0x1b, 0x23, 0xe8, 0x1b, 0x78, 0x63, 0x91, 0xf0, 0xe1, 0x4b, 0x26, 0xd7, 0x26,
	0x25, 0x36, 0x1b, 0x7b, 0xb2, 0x19, 0x1d, 0x04, 0x06, 0x50, 0x37, 0x3d, 0x25, 0x4b, 0xb9, 0x5f,
	0xee, 0x91, 0xd0, 0x8b, 0x0a, 0x8d, 0x3e, 0xd4, 0x96, 0x89, 0x8a, 0xd7, 0xd3, 0x91, 0xef, 0xd8,
	0x6e, 0x47, 0x89, 0x5d, 0x00, 0xad, 0x34, 0x4b, 0x06, 0x46, 0xfb, 0x15, 0x1b, 0x3c, 0x21, 0xb4,
	0x0b, 0xf5, 0xf1, 0xb1, 0x0a, 0x42, 0xc5, 0x56, 0x27, 0xb6, 0xba, 0xdd, 0xd3, 0x77, 0x02, 0x0d,
	0x93, 0x30, 0xcf, 0xd2, 0x94, 0x6d, 0xf7, 0xf8, 0x17, 0x1a, 0xf6, 0x3a, 0x8b, 0x58, 0x65, 0xf2,
	0xe8, 0x0d, 0x2c, 0x1a, 0x1a, 0x82, 0x1d, 0x80, 0xe5, 0x5e, 0xf3, 0x3c, 0x5e, 0xb6, 0x71, 0xcf,
	0x90, 0x43, 0xf8, 0x1f, 0x34, 0x79, 0xc2, 0x36, 0x3b, 0xbe, 0x5a, 0x68, 0x91, 0xf2, 0xfc, 0xba,
	0x8d, 0x9c, 0x3d, 0x8a, 0x73, 0x33, 0x95, 0x6b, 0x66, 0xaa, 0x97, 0x66, 0x0a, 0x03, 0xee, 0x97,
	0x81, 0x9b, 0x0f, 0x72, 0x78, 0xda, 0x89, 0xf9, 0x2b, 0xbc, 0x87, 0xfa, 0x9c, 0xbd, 0x72, 0x03,
	0xb0, 0xd5, 0x2f, 0xfe, 0xb0, 0x5f, 0x3c, 0x7e, 0xd0, 0xbe, 0xa0, 0xb9, 0x71, 0x5a, 0x0a, 0x09,
	0xde, 0x41, 0x6d, 0xc2, 0xb5, 0x3d, 0xfc, 0xe7, 0x22, 0xcd, 0xf4, 0x0a, 0x7e, 0xac, 0x48, 0x4b,
	0xff, 0x09, 0xce, 0xe0, 0xd7, 0xf9, 0x8c, 0x60, 0xe7, 0x24, 0xf7, 0xfb, 0xf8, 0x04, 0xd7, 0xc3,
	0xb4, 0xb4, 0x74, 0xed, 0x1c, 0xde, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xb4, 0x75, 0x1a,
	0x9b, 0x02, 0x00, 0x00,
}
